project_id = "gphqejlpxntpkajzcbcn"

[functions.send-quote-email]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-drinks]
verify_jwt = false

[functions.notify-home-visit]
verify_jwt = false

[functions.create-notion-event]
verify_jwt = false
